name: Run Unit Tests via Pytest

on: [push]

env:
  SLOG_ROOT_DIR: "${{ github.workspace }}/slog_repo"
  PYPROJECT_TOLM: "${{ github.workspace }}/slog_repo/pyproject.toml"
  VENV_ROOT_DIR: "${{ github.workspace }}"
  PYTHONPATH: "${{ github.workspace }}/slog_repo"

jobs:
  basic_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}/slog_repo

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      id: setup_uv
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Python
      run: uv python install

    - name: Install Dependencies for each environment
      run: |
        uv venv core_only
        source $VENV_ROOT_DIR/core_only/bin/activate
        deactivate

    - name: Test core_only with unittest
      if: always()
      run: |
        source $VENV_ROOT_DIR/core_only/bin/activate
        python -m slog tests -u

    - name: Test docstrings
      if: always()
      run: |
        source $VENV_ROOT_DIR/core_only/bin/activate
        python -m slog tests -d

  static:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}/slog_repo

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      id: setup_uv
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Python
      run: uv python install

    - name: Install Dependencies for each environment
      run: |
        uv venv static
        source $VENV_ROOT_DIR/static/bin/activate
        uv pip install black isort mypy pylint pylint-exit pytest-cov ruff ty
        deactivate

    - name: Mypy static analysis
      working-directory: ${{ env.SLOG_ROOT_DIR }}
      if: always()
      run: |
        source $VENV_ROOT_DIR/static/bin/activate
        python --version
        mypy --version
        mypy

    - name: Ruff static analysis
      working-directory: ${{ env.SLOG_ROOT_DIR }}
      if: always()
      run: |
        source $VENV_ROOT_DIR/static/bin/activate
        python --version
        ruff --version
        ruff check .

    - name: Ty static analysis
      working-directory: ${{ env.SLOG_ROOT_DIR }}
      if: always()
      run: |
        source $VENV_ROOT_DIR/static/bin/activate
        python --version
        ty --version
        ty check .

    - name: Pylint static analysis
      working-directory: ${{ env.SLOG_ROOT_DIR }}
      if: always()
      run: |
        source $VENV_ROOT_DIR/static/bin/activate
        python --version
        pylint --version
        pylint . || pylint-exit $?

    - name: black static analysis
      working-directory: ${{ env.SLOG_ROOT_DIR }}
      if: always()
      run: |
        source $VENV_ROOT_DIR/static/bin/activate
        python --version
        black --version
        black . --check --fast

    - name: isort static analysis
      working-directory: ${{ env.SLOG_ROOT_DIR }}
      if: always()
      run: |
        source $VENV_ROOT_DIR/static/bin/activate
        isort --version
        isort . --check-only --diff

  full_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}/slog_repo

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      id: setup_uv
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Python
      run: uv python install

    - name: Install Dependencies for each environment
      run: |
        uv venv core_only
        source $VENV_ROOT_DIR/core_only/bin/activate
        uv pip install pytest-cov
        deactivate

    - name: Run coverage report
      working-directory: ${{ env.SLOG_ROOT_DIR }}
      if: always()
      run: |
        source $VENV_ROOT_DIR/core_only/bin/activate
        python -m slog tests --coverage --cov_file $SLOG_ROOT_DIR/.coverage

    - name: Make the coverage reports
      working-directory: ${{ env.SLOG_ROOT_DIR }}
      run: |
        source $VENV_ROOT_DIR/core_only/bin/activate
        export COVERAGE_FILE=.coverage
        export COVERAGE_RCFILE=$PYPROJEC_TOLM
        coverage --version
        coverage html --rcfile $PYPROJECT_TOLM
        coverage xml --rcfile $PYPROJECT_TOLM
        coverage json --rcfile $PYPROJECT_TOLM

  old_versions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}/slog_repo

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      id: setup_uv
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Python
      run: uv python install

    - name: Install Dependencies and run tests
      run: |
        uv venv old_version
        source $VENV_ROOT_DIR/old_version/bin/activate
        uv pip install pytest-cov
        python -m slog tests
        deactivate
